version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    container_name: grida-database
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: 'Asia/Seoul'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  grida-sso-app:
    depends_on:
      - database
    image: wwan13/grida-sso-app:prod
    container_name: grida-sso-app
    ports:
      - "8070:8070"
    restart: always
    env_file:
      - "./.env"

  grida-end-user-app:
    depends_on:
      - database
    image: wwan13/grida-end-user-app:prod
    container_name: grida-end-user-app
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - "./.env"

  grida-trial-user-app:
    depends_on:
      - database
    image: wwan13/grida-trial-user-app:prod
    container_name: grida-trial-user-app
    ports:
      - "8090:8090"
    restart: always
    env_file:
      - "./.env"

  nginx:
    depends_on:
      - database
      - grida-sso-app
      - grida-end-user-app
      - grida-trial-user-app
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: grida-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    depends_on:
      - database
      - grida-sso-app
      - grida-end-user-app
      - grida-trial-user-app
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"