server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include:
      - core
      - apis-core
      - apis-security
      - awss3-client
      - cdn-client
      - domain
      - domain-rds
      - domain-image
      - domain-ai