spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expired: ${ACCESS_TOKEN_EXPIRED}
  refresh-token-expired: ${REFRESH_TOKEN_EXPIRED}
