## ??
spring:
  profiles:
    include:
      - core
      - common
      - infrastructure
      - security
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 9999
    open-in-view: false
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB