storage:
  cdn:
    domain: https://storage.gridadiary.site
  aws:
    access-key: access-key
    secret-key: secret-key
    region: ap-northeast-2
    bucket: arn:aws:s3:::grida-storage

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2